/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Component;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.datacontract.schemas._2004._07.wcfservicetempconversion.ArrayOfConversion;
import org.datacontract.schemas._2004._07.wcfservicetempconversion.Conversion;

/**
 *
 * @author mybde
 */
public class FenTemp extends javax.swing.JFrame {
    /**
     * Creates new form FenTemp
     */
    public FenTemp() {
        initComponents();
        afficherTableAppel(getAll(), jTableAppel);
        rbtnCelcius.setSelected(true);
        txtValeur.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnConvertir = new javax.swing.JButton();
        txtValeur = new javax.swing.JTextField();
        rbtnCelcius = new javax.swing.JRadioButton();
        rbtnFahrenheit = new javax.swing.JRadioButton();
        lblResultat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAppel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnCelcius);
        rbtnCelcius.setText("Celcius");

        buttonGroup1.add(rbtnFahrenheit);
        rbtnFahrenheit.setText("Fahrenheit");

        jLabel1.setText("Saisir la valeur à convertir");

        jTableAppel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User name", "Machine name", "Temp", "Date appel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAppel);
        if (jTableAppel.getColumnModel().getColumnCount() > 0) {
            jTableAppel.getColumnModel().getColumn(0).setResizable(false);
            jTableAppel.getColumnModel().getColumn(1).setResizable(false);
            jTableAppel.getColumnModel().getColumn(2).setMinWidth(60);
            jTableAppel.getColumnModel().getColumn(2).setPreferredWidth(60);
            jTableAppel.getColumnModel().getColumn(2).setMaxWidth(60);
            jTableAppel.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setText("en");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtValeur, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(9, 9, 9)
                                .addComponent(rbtnCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnFahrenheit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 184, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtValeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtnCelcius)
                        .addComponent(rbtnFahrenheit)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnConvertir)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        // TODO add your handling code here:
        double valeur = Double.parseDouble(txtValeur.getText());

        if (rbtnCelcius.isSelected()) {
            try {
                double retour = convertirVersCelcius(Double.parseDouble(txtValeur.getText()), System.getProperty("user.name"), InetAddress.getLocalHost().getHostName());
                
                lblResultat.setText(String.valueOf(retour));
            } catch (UnknownHostException ex) {
                Logger.getLogger(FenTemp.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                double retour = convertirVersFarh(Double.parseDouble(txtValeur.getText()), System.getProperty("user.name"), InetAddress.getLocalHost().getHostName());
                lblResultat.setText(String.valueOf(retour));
            } catch (UnknownHostException ex) {
                Logger.getLogger(FenTemp.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        afficherTableAppel(getAll(), jTableAppel);
    }//GEN-LAST:event_btnConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenTemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenTemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAppel;
    private javax.swing.JLabel lblResultat;
    private javax.swing.JRadioButton rbtnCelcius;
    private javax.swing.JRadioButton rbtnFahrenheit;
    private javax.swing.JTextField txtValeur;
    // End of variables declaration//GEN-END:variables

    private static Double convertirVersCelcius(java.lang.Double temp, java.lang.String userName, java.lang.String machineName) {
        org.tempuri.ServiceConversion service = new org.tempuri.ServiceConversion();
        org.tempuri.IServiceConversion port = service.getBasicHttpBindingIServiceConversion();
        return port.convertirVersCelcius(temp, userName, machineName);
    }

    private static Double convertirVersFarh(java.lang.Double temp, java.lang.String userName, java.lang.String machineName) {
        org.tempuri.ServiceConversion service = new org.tempuri.ServiceConversion();
        org.tempuri.IServiceConversion port = service.getBasicHttpBindingIServiceConversion();
        return port.convertirVersFarh(temp, userName, machineName);
    }

    private static ArrayOfConversion getAll() {
        org.tempuri.ServiceConversion service = new org.tempuri.ServiceConversion();
        org.tempuri.IServiceConversion port = service.getBasicHttpBindingIServiceConversion();
        return port.getAll();
    }
    
    ///A reprendre
    private void afficherTableAppel(ArrayOfConversion listAppel, JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (Conversion conversion : listAppel.getConversion()) {
            model.addRow(new Object[]{conversion.getUserName().getValue(), conversion.getMachineName().getValue(), conversion.getValeur(),conversion.getDateAppel().toGregorianCalendar().getTime()});
        }
    }
}
